/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tugas_akhir_milleano;

import javax.swing.JOptionPane;

/**
 *
 * @author MILLEANO ADI SANTIKO
 */
public class TugasAhirMilleano extends javax.swing.JFrame {

    public String coba(){
    return "------Selamat Datang------";
    }
        
    /** Creates new form TugasAhirMilleano */
    public TugasAhirMilleano() {
        initComponents();
        
        kelasta objekk = new kelasta();
        objekk.setTes("\nDi Milleano Futsal Stadium.");
        objekk.setTess("Junjung tinggi sportivitas!");
        objekk.setTesss("\nFighting on Spirit, \nKeep Solidarity, \nAnd Humanity.");
        
        kolomHasil.setText(coba() + "\n" + objekk.getTes() + "\n" + objekk.getTess() + "\n" + objekk.getTesss());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kolomNama = new javax.swing.JTextField();
        kolomTelepon = new javax.swing.JTextField();
        kolomLamaSewa = new javax.swing.JTextField();
        kolomWaktu = new javax.swing.JTextField();
        kolomLapangan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kolomHasil = new javax.swing.JTextArea();
        btnEXIT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ini Form Milleano Futsal Stadium");
        setLocation(new java.awt.Point(500, 250));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kolomNama.setBackground(new java.awt.Color(240, 240, 240));
        kolomNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomNamaActionPerformed(evt);
            }
        });
        getContentPane().add(kolomNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 240, 50));

        kolomTelepon.setBackground(new java.awt.Color(240, 240, 240));
        kolomTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomTeleponActionPerformed(evt);
            }
        });
        getContentPane().add(kolomTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 240, 50));

        kolomLamaSewa.setBackground(new java.awt.Color(240, 240, 240));
        kolomLamaSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomLamaSewaActionPerformed(evt);
            }
        });
        getContentPane().add(kolomLamaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 240, 50));

        kolomWaktu.setBackground(new java.awt.Color(240, 240, 240));
        kolomWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomWaktuActionPerformed(evt);
            }
        });
        getContentPane().add(kolomWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 240, 50));

        kolomLapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Lapangan", "Lapangan A", "Lapangan B", "Lapangan C", "Lapangan D" }));
        getContentPane().add(kolomLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 240, 50));

        jButton1.setText("BOOK!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 100, 40));

        kolomHasil.setEditable(false);
        kolomHasil.setColumns(20);
        kolomHasil.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        kolomHasil.setRows(5);
        jScrollPane1.setViewportView(kolomHasil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 230, 310));

        btnEXIT.setText("EXIT!");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });
        getContentPane().add(btnEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_akhir_milleano/Capture.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolomNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomNamaActionPerformed

    private void kolomTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomTeleponActionPerformed

    private void kolomLamaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomLamaSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomLamaSewaActionPerformed

    private void kolomWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomWaktuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
String nama,telepon,lama,waktu;
int harga = 0;
Integer jam = Integer.parseInt(kolomLamaSewa.getText());
nama = kolomNama.getText();
telepon = kolomTelepon.getText();
waktu = kolomWaktu.getText();
lama = kolomLamaSewa.getText();


int lapangan = kolomLapangan.getSelectedIndex();
switch (lapangan){
    case 1 : 
        harga = 100000;
        break;
    case 2 : 
        harga = 125000;
        break;
    case 3 : 
        harga = 150000;
         break;
    case 4 : 
        harga = 175000;
        break;
}
int total = harga*jam;
kolomHasil.setText("Nama        : "+ nama + "\nTelepon     : "+ telepon + "\nLama Sewa   : " + lama + " Jam" + "\nWaktu       : " + waktu + " WIB" + "\n=========================\nTotal Bayar : " + "Rp. "+ Integer.toString(total) + "\n\n\n\n\n\n\n\n       Terima Kasih" + "\n      Salam Olahraga" + "\nSemoga Harimu Menyenangkan");
}
catch (Exception e){
kolomHasil.setText("Masukan input dengan benar!");
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
        Integer EXIT = JOptionPane.showConfirmDialog(this,
                "Apakah Anda Ingin Keluar?",
                "PERHATIAN!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
                if (JOptionPane.YES_OPTION == EXIT){
                    System.exit(0);
                }
    }//GEN-LAST:event_btnEXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasAhirMilleano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasAhirMilleano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasAhirMilleano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasAhirMilleano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasAhirMilleano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEXIT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea kolomHasil;
    private javax.swing.JTextField kolomLamaSewa;
    private javax.swing.JComboBox<String> kolomLapangan;
    private javax.swing.JTextField kolomNama;
    private javax.swing.JTextField kolomTelepon;
    private javax.swing.JTextField kolomWaktu;
    // End of variables declaration//GEN-END:variables

}
